version: 2

general:
    branches:
        only:
            - dev

jobs:
    build:
        docker: 
            - image: nm73/docker-hugo:latest
              entrypoint: docker-entrypoint.sh
        steps:
            - checkout
            - run: run.sh
workflow:
    version: 2
    build_and_deploy:
        jobs:
            - build

